name: Reusable Auto-Label

on:
  workflow_call: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR by size and paths
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/labeler@v5
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Size label
        uses: codelytv/pr-size-labeler@v1
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/xs"
          xs_max_size: "10"
          s_label: "size/s"
          s_max_size: "100"
          m_label: "size/m"
          m_max_size: "500"
          l_label: "size/l"
          l_max_size: "1000"
          xl_label: "size/xl"
